version: '3.8'

services:
  stable-db:
    image: postgres:14
    container_name: canary-stable
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stable_db
    ports:
      - "5454:5432"

  canary-db:
    image: postgres:14
    container_name: canary-canary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: canary_db
    ports:
      - "5455:5432"

volumes:
  stable_data:
  canary_data:
